### ISSUE TITLE
make filename consistent with npm name, or teach webpack

### ISSUE THREAD

**Issue by gordonwoodhull** [crossfilter/crossfilter#75]
Hi @esjewett, 

dc.js users are in an uproar over the incompatibility we've introduced with webpack by making the npm name different from the filename. 

well, not really an uproar, but people keep opening more issues about it. (latest is dc-js/dc.js#1302)

I propose that we either
 1. learn webpack (sigh, another framework that will be obsolete by the time we learn it) and include some webpack config in crossfilter to alias crossfilter to crossfilter2
 2. change the filename to match the npm name.

Thoughts?

**Comment by esjewett** [comment]
Funny enough, I'm actually using webpack on another project now, but am not using dc.js or Crossfilter on that project, so...

What would be awesome is if we can get someone to put together a super-simple example project that displays this problem. I suspect the fix will be changing the `require` in dc.js's `index.js` to be `require('crossfilter2')`. I'm actually a little surprised the current one is working. Does your build system just alias requires out to the corresponding global variable?

**Comment by esjewett** [comment]
@gordonwoodhull Looking at the `concat` step of your grunt file, it looks like `index.js` is ignored. Can you update the `require` in that file without impacting your bundles? If so, it would be worth a try to see if it fixes this problem.

**Comment by gordonwoodhull** [comment]
I have no idea. `index.js` was contributed years ago to enable Node and browserify - I doubt it is intended to help webpack.

You're right that we'll need an example demonstrating the problem.

**Comment by esjewett** [comment]
My thinking is that Webpack just uses node module resolution. So since there is no `main` file defined in the dc.js `package.json`, webpack will start at the `index.js` by default. When it sees `require('crossfilter')` it will try to resolve that against the directory of the same name in the `node_modules` directory. That will fail because the module and directory are actually called `crossfilter2`.

**Comment by gordonwoodhull** [comment]
That would make sense, however the suggested solutions have all involved changing the AMD (!!) path in dc.js. Which I find very confusing, because webpack is a compilation step and not asynchronous at all.

I.e. dc-js/dc.js#1204 suggests changing


```js
if(typeof define === "function" && define.amd) {
  define(["d3", "crossfilter"], _dc);
}
```

to

```js
define(["d3", "crossfilter2"], _dc);
```

**Comment by esjewett** [comment]
You are right, that is the fix. I've created a working (e.g. broken) example here: https://github.com/esjewett/dcjs-webpack-example

Running webpack on this results in a compilation error. Webpack tries to resolve the `define` at compile time and fails because there is no `crossfilter` module installed. To verify, do `npm install crossfilter` and then run webpack and it will work.

Looking at the `define` spec, the strings in the array that is the first argument are supposed to be the literal module names, so this makes some sense. Would changing it to `define(["d3", "crossfilter2"], _dc);` break anything that we know of?

**Comment by gordonwoodhull** [comment]
Yes, it will break AMD, which expects the filename not the module name. 

This is the essential conflict between webpack's view of the world and the AMD view of the world.

**Comment by esjewett** [comment]
Got it. Let me see if I can force webpack to behave somehow here...

**Comment by esjewett** [comment]
To expand on that, I suppose we could just change the filename so that AMD works with `crossfilter2`. But if that's what AMD is basing this off of, then changing that filename will break all existing AMD. Is that correct?

**Comment by gordonwoodhull** [comment]
I think it will "only" break all manual configurations out in the world. Libraries such as dc.js and family will have an npm dependency of crossfilter2 >= 1.5 (say) so as long as they have been npm-installed, they should be okay.

I don't think it's the manual configuration that has people up in arms, it's that in many cases they have to actually go in and change a line inside `node_modules` (if they don't have control over the webpack config).

That said, I agree it'd be nicer if crossfilter2 could just have some kind of auxiliary webpack config (or if it took the index.js route instead of AMD route, or something) so that we didn't have to change the filename.

**Comment by esjewett** [comment]
There is something I am not understanding here, but I don't see what it is. Do we have an example application making use of the AMD loading that will break if we change that line in dc.js?

**Comment by gordonwoodhull** [comment]
I can work up a simple self-contained example, but not today. My actual use case is pretty complex, because we use dc.js as a data exploration tool in RCloud:

https://rcloud.social/view.html?notebook=4c0b068d7daad696453b

Conceivably, crossfilter2 could also meddle with the requireJS configuration (which also has aliases), but there doesn't seem to be any standard place to put this (it's just a JS object).

**Comment by esjewett** [comment]
I've put together a basic example here: https://github.com/esjewett/dcjs-requirejs-example

However, it doesn't look to me like Crossfilter properly exports an object with requireJS (dc.js does), so I don't see how AMD is working at all anywhere. I am probably doing it wrong.

**Comment by esjewett** [comment]
BTW - I can't see that notebook. Do you have one you can make publicly accessible?

**Comment by gordonwoodhull** [comment]
Sorry, I've published the notebook now. (You could also log into rcloud.social with github, as it's a public demo.)

Crossfilter doesn't really need to register with AMD/requireJS because it has no dependencies. That said, I think at some point someone added UMD (including AMD) support to crossfilter when they were generally upgrading the build. So the first line of crossfilter.js 1.4 does do AMD.

**Comment by gordonwoodhull** [comment]
Thanks - I can build out that example. Unfortunately I'm on a completely different deadline today so I have to drop out of this conversation. (Even though it's a lot more fun.)

**Comment by esjewett** [comment]
Thanks - I've got the example working now. Clearly works with `crossfilter.js` and not with `crossfilter2.js`.

Thoughts:
- Require.js appears to require as a convention that the module filename and the module export have the same name (we do - `crossfilter`).
- Require.js still appears to work if we rename the file to `crossfilter2.js` and using `define(['crossfilter2',...`
- Webpack wants, by default, to resolve the exact string used in `define` as an npm module, meaning that it will try to resolve this to `crossfilter` when we are using the `crossfilter2` modules
- Webpack, and more specifically, CommonJS and NPM modules with build tools are the new thing and appear to be the future
- AMD and Require.js are out there but seem to be on the way out
- Angular-cli doesn't allow overriding its own internal `webpack.config.js`
- All the Require.js uses I've seen vendor their dependencies, so you have local control over the filename in that scenario, theoretically
- Changing the filename of the main file in the Crossfilter project won't fix the Webpack problem because it is looking in the wrong *folder*, not for the wrong file.

So what do we do? Options I see:

- Update dc.js to use `'crossfilter2` in its `define`. Say that if people want to use Crossfilter2 with Require.js they need to change the filename when they vendor it. Downside: this is fiddly for Require.js users.
- Update dc.js to use `'crossfilter2` in its `define`. Change the main filename of the Crossfilter project to `crossfilter2.js`. Downside: This is going to break anyone directly referencing that file in `node_modules`, `bower_modules`, or via CDN.
- Update dc.js to use `'crossfilter2` in its `define`. *Add* a `crossfilter2.js` file to the Crossfilter distribution that is a copy of `crossfilter.js`. Downside: Require.js users will still need to grab the right file to vendor, and this will increase the size of our distribution
- Leave things as-is. Webpack with dc.js will require the `resolve` override for Crossfilter. Angular-cli will not work (unless they are willing to add this `resolve` override to their own webpack configuration)
- There may be some way to do the `define` call in dc.js that webpack will ignore. I don't know what this is.

If I had to pick one here, it would be the first option. It doesn't break anything immediately because Require.js users will have their dependencies vendored already, and the error when they do update dc.js will be fairly intuitive to address because it will say that it can't find `crossfilter2.js`.

**Comment by gordonwoodhull** [comment]
Fair enough. Out with the old, in with the new, I guess it is. You are right that when there is no automatic package resolution, there is a copy step where the filename can be changed.

Thanks for puzzling this out!
